[git_metrics]
disabled = true
added_style = 'bold blue'
format = '([+$added]($added_style) )([-$deleted]($deleted_style) | )'

[git_status]
style = 'gray'
format = '[$all_status(| $ahead_behind)]($style)'
ahead = '[â†‘${count} ](yellow)'
diverged = 'ğŸ¥´â†‘${ahead_count}â†“${behind_count}'
behind = 'â†“${count}'
staged = '[â¬¤${count} ](yellow)'
untracked = '[?${count} ](bold gray)'
conflicted = '[âŒ{count}](bold red)'
modified = '[+${count} ](bold blue)'
deleted = '[x${count}](bold #DF0F96) '
stashed = '(ğŸ“‚ $count )'

[nodejs]
disabled = true

[python]
disabled = false
format = '[(\($virtualenv\)) ](bold yellow)'

[package]
disabled = true

[rlang]
disabled = true

[bun]
disabled = true
